# Generated by Django 4.2.3 on 2023-08-19 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My first chatbot', max_length=255)),
                ('website', models.CharField(default='https://openchat.so', max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('prompt_message', models.TextField(blank=True, default="Use the following pieces of context to answer the question at the end. \n    If you don't know the answer, just say that you don't know, don't try to make up an answer. \n    Use three sentences maximum and keep the answer as concise as possible. \n    {context}\n    Question: {question}\n    Helpful Answer:")),
                ('token', models.CharField(max_length=255)),
                ('enhanced_privacy', models.BooleanField(default=False)),
                ('smart_sync', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'chatbots',
            },
        ),
        migrations.CreateModel(
            name='ChatbotSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chatbot_id', models.CharField(max_length=36, null=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_settings',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('chatbot_id', models.CharField(max_length=36, null=True)),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('from_user', models.CharField(db_column='from', max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_histories',
            },
        ),
        migrations.CreateModel(
            name='CodebaseDataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository', models.CharField(max_length=255)),
                ('chatbot_id', models.CharField(max_length=36, null=True)),
                ('ingested_at', models.DateTimeField()),
                ('ingestion_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'codebase_data_sources',
            },
        ),
        migrations.CreateModel(
            name='FailedJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255)),
                ('connection', models.TextField()),
                ('queue', models.TextField()),
                ('payload', models.TextField()),
                ('exception', models.TextField()),
                ('failed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'failed_jobs',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('queue', models.CharField(max_length=255)),
                ('payload', models.TextField()),
                ('attempts', models.PositiveIntegerField()),
                ('reserved_at', models.PositiveIntegerField(null=True)),
                ('available_at', models.PositiveIntegerField()),
                ('created_at', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='NotionDataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notion_data_sources',
            },
        ),
        migrations.CreateModel(
            name='OnboardingSteps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chatbot_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onboarding_steps',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='PdfDataSource',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('chatbot_id', models.CharField(max_length=36, null=True)),
                ('files', models.JSONField()),
                ('folder_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ingest_status', models.CharField(default='success', max_length=255)),
            ],
            options={
                'db_table': 'pdf_data_sources',
            },
        ),
        migrations.CreateModel(
            name='PersonalAccessToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tokenable_type', models.CharField(max_length=255)),
                ('tokenable_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=64)),
                ('abilities', models.TextField(null=True)),
                ('last_used_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personal_access_tokens',
            },
        ),
        migrations.CreateModel(
            name='TextDataSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'text_data_sources',
            },
        ),
        migrations.CreateModel(
            name='WebsiteDataSource',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('chatbot_id', models.CharField(max_length=36, null=True)),
                ('root_url', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255, null=True)),
                ('vector_databased_last_ingested_at', models.DateTimeField(null=True)),
                ('crawling_status', models.CharField(default='pending', max_length=255)),
                ('crawling_progress', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'website_data_sources',
            },
        ),
        migrations.CreateModel(
            name='CrawledPages',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('chatbot_id', models.CharField(max_length=36, null=True)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, null=True)),
                ('status_code', models.CharField(max_length=255, null=True)),
                ('aws_url', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website_data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawled_pages', to='web.websitedatasource')),
            ],
            options={
                'db_table': 'crawled_pages',
            },
        ),
    ]
