# Generated by Django 4.2.3 on 2023-08-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotsetting',
            name='chatbot_id',
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='chatbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='web.chatbot'),
        ),
        migrations.AlterField(
            model_name='codebasedatasource',
            name='chatbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codebase_data_sources', to='web.chatbot'),
        ),
        migrations.AlterModelTable(
            name='chatbot',
            table='chatbots',
        ),
        migrations.AlterModelTable(
            name='chatbotsetting',
            table='chatbot_settings',
        ),
        migrations.AlterModelTable(
            name='chathistory',
            table='chat_histories',
        ),
        migrations.AlterModelTable(
            name='codebasedatasource',
            table='codebase_data_sources',
        ),
        migrations.AlterModelTable(
            name='pdfdatasource',
            table='pdf_data_sources',
        ),
        migrations.AlterModelTable(
            name='personalaccesstoken',
            table='personal_access_tokens',
        ),
        migrations.AlterModelTable(
            name='websitedatasource',
            table='website_data_sources',
        ),
    ]
