# Generated by Django 4.2.3 on 2023-08-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebasedatasource',
            name='chatbot_id',
            field=models.UUIDField(null=True),
        ),
    ]
