# Generated by Django 4.2.3 on 2023-10-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdatasource',
            name='chatbot_id',
        ),
        migrations.AddField(
            model_name='pdfdatasource',
            name='chatbot',
            field=models.ForeignKey(db_column='chatbot_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_data_sources', to='web.chatbot'),
        ),
    ]
