# Generated by Django 4.2.3 on 2023-07-29 12:42

from django.db import migrations, models
import web.enums.chatbot_initial_prompt_enum


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(default='My first chatbot', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='prompt_message',
            field=models.TextField(blank=True, default=web.enums.chatbot_initial_prompt_enum.ChatBotInitialPromptEnum['AI_ASSISTANT_INITIAL_PROMPT']),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='website',
            field=models.CharField(default='https://openchat.so', max_length=255),
        ),
    ]
