# Generated by Django 4.2.3 on 2023-07-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_chatbot_name_alter_chatbot_prompt_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='prompt_message',
            field=models.TextField(blank=True, default="You are a helpful AI customer support agent. Use the following pieces of context to answer the question at the end.\nIf you don't know the answer, just say you don't know. DO NOT try to make up an answer.\nIf the question is not related to the context, politely respond that you are tuned to only answer questions that are related to the context.\n\n{context}\n\nQuestion: {question}\nHelpful answer in markdown:"),
        ),
        migrations.AlterField(
            model_name='websitedatasource',
            name='html_files',
            field=models.JSONField(default=list),
        ),
    ]
