# Generated by Django 4.2.3 on 2023-10-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_pdfdatasource_chatbot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdatasource',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
