# Generated by Django 4.2.3 on 2023-08-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_codebasedatasource_chatbot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebasedatasource',
            name='chatbot_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
