# Generated by Django 4.2.3 on 2023-10-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_pdfdatasource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatasource',
            name='files_info',
            field=models.JSONField(null=True),
        ),
    ]
