# Generated by Django 4.2.3 on 2023-07-30 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_chatbot_prompt_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chathistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='websitedatasource',
            name='vector_databased_last_ingested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
