# Generated by Django 4.2.3 on 2023-07-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_chathistory_created_at_chathistory_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpages',
            name='content_file',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
