# Generated by Django 4.2.3 on 2023-08-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_crawledpages_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='prompt_message',
            field=models.TextField(blank=True, default='Use the following pieces of context to answer the question at the end. \n    If you don\'t know the answer, just say that you don\'t know, don\'t try to make up an answer. \n    Use three sentences maximum and keep the answer as concise as possible. \n    Always say "thanks for asking!" at the end of the answer. \n    {context}\n    Question: {question}\n    Helpful Answer:'),
        ),
    ]
