# Generated by Django 4.2.3 on 2023-10-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_pdfdatasourceerrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpages',
            name='content_file',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
