# Generated by Django 4.2.3 on 2023-10-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_crawledpages_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfDataSourceErrorLog',
        ),
    ]
