# Generated by Django 4.2.3 on 2023-12-29 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0008_delete_pdfdatasourceerrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
