# Generated by Django 4.2.3 on 2024-02-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_chatbot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='feedback',
            field=models.BooleanField(blank=True, help_text='Feedback indicating if the response was helpful', null=True),
        ),
    ]
