# Generated by Django 4.2.3 on 2023-07-21 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodebaseDataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chatbot_id', models.UUIDField()),
                ('repository', models.CharField(max_length=255)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'codebase_data_sources',
            },
        ),
        migrations.CreateModel(
            name='NotionDataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notion_data_sources',
            },
        ),
    ]
